// Plaid Personal Finance Category (PFC) taxonomy.
// Source: https://plaid.com/docs/api/products/transactions/#categoriesget
//
// Three-level hierarchy used in the budget UI:
//   Group (Income / Expenses) → Category (PFC primary) → Subcategory (PFC detailed)
//
// Budgets live at the subcategory (detailed) level. Categories and groups
// display rolled-up totals.

export type PfcGroup = "INCOME" | "EXPENSES";

export const PLAID_PFC_PRIMARY = [
  "INCOME",
  "TRANSFER_IN",
  "TRANSFER_OUT",
  "LOAN_PAYMENTS",
  "BANK_FEES",
  "ENTERTAINMENT",
  "FOOD_AND_DRINK",
  "GENERAL_MERCHANDISE",
  "HOME_IMPROVEMENT",
  "MEDICAL",
  "PERSONAL_CARE",
  "GENERAL_SERVICES",
  "GOVERNMENT_AND_NON_PROFIT",
  "TRANSPORTATION",
  "TRAVEL",
  "RENT_AND_UTILITIES",
] as const;

export type PfcPrimary = (typeof PLAID_PFC_PRIMARY)[number];

// Full Plaid PFC detailed → primary map. The detailed code's prefix matches
// its primary, but enumerating explicitly avoids brittle string parsing.
export const PFC_DETAILED: Record<string, PfcPrimary> = {
  // Income
  INCOME_DIVIDENDS: "INCOME",
  INCOME_INTEREST_EARNED: "INCOME",
  INCOME_RETIREMENT_PENSION: "INCOME",
  INCOME_TAX_REFUND: "INCOME",
  INCOME_UNEMPLOYMENT: "INCOME",
  INCOME_WAGES: "INCOME",
  INCOME_OTHER_INCOME: "INCOME",

  // Transfers In
  TRANSFER_IN_CASH_ADVANCES_AND_LOANS: "TRANSFER_IN",
  TRANSFER_IN_DEPOSIT: "TRANSFER_IN",
  TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS: "TRANSFER_IN",
  TRANSFER_IN_SAVINGS: "TRANSFER_IN",
  TRANSFER_IN_ACCOUNT_TRANSFER: "TRANSFER_IN",
  TRANSFER_IN_OTHER_TRANSFER_IN: "TRANSFER_IN",

  // Transfers Out
  TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS: "TRANSFER_OUT",
  TRANSFER_OUT_SAVINGS: "TRANSFER_OUT",
  TRANSFER_OUT_WITHDRAWAL: "TRANSFER_OUT",
  TRANSFER_OUT_ACCOUNT_TRANSFER: "TRANSFER_OUT",
  TRANSFER_OUT_OTHER_TRANSFER_OUT: "TRANSFER_OUT",

  // Loan Payments
  LOAN_PAYMENTS_CAR_PAYMENT: "LOAN_PAYMENTS",
  LOAN_PAYMENTS_CREDIT_CARD_PAYMENT: "LOAN_PAYMENTS",
  LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT: "LOAN_PAYMENTS",
  LOAN_PAYMENTS_MORTGAGE_PAYMENT: "LOAN_PAYMENTS",
  LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT: "LOAN_PAYMENTS",
  LOAN_PAYMENTS_OTHER_PAYMENT: "LOAN_PAYMENTS",

  // Bank Fees
  BANK_FEES_ATM_FEES: "BANK_FEES",
  BANK_FEES_FOREIGN_TRANSACTION_FEES: "BANK_FEES",
  BANK_FEES_INSUFFICIENT_FUNDS: "BANK_FEES",
  BANK_FEES_INTEREST_CHARGE: "BANK_FEES",
  BANK_FEES_OVERDRAFT_FEES: "BANK_FEES",
  BANK_FEES_OTHER_BANK_FEES: "BANK_FEES",

  // Entertainment
  ENTERTAINMENT_CASINOS_AND_GAMBLING: "ENTERTAINMENT",
  ENTERTAINMENT_MUSIC_AND_AUDIO: "ENTERTAINMENT",
  ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS: "ENTERTAINMENT",
  ENTERTAINMENT_TV_AND_MOVIES: "ENTERTAINMENT",
  ENTERTAINMENT_VIDEO_GAMES: "ENTERTAINMENT",
  ENTERTAINMENT_OTHER_ENTERTAINMENT: "ENTERTAINMENT",

  // Food & Drink
  FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR: "FOOD_AND_DRINK",
  FOOD_AND_DRINK_COFFEE: "FOOD_AND_DRINK",
  FOOD_AND_DRINK_FAST_FOOD: "FOOD_AND_DRINK",
  FOOD_AND_DRINK_GROCERIES: "FOOD_AND_DRINK",
  FOOD_AND_DRINK_RESTAURANT: "FOOD_AND_DRINK",
  FOOD_AND_DRINK_VENDING_MACHINES: "FOOD_AND_DRINK",
  FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK: "FOOD_AND_DRINK",

  // General Merchandise
  GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_CONVENIENCE_STORES: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_DEPARTMENT_STORES: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_DISCOUNT_STORES: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_ELECTRONICS: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_OFFICE_SUPPLIES: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_ONLINE_MARKETPLACES: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_PET_SUPPLIES: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_SPORTING_GOODS: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_SUPERSTORES: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_TOBACCO_AND_VAPE: "GENERAL_MERCHANDISE",
  GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE: "GENERAL_MERCHANDISE",

  // Home Improvement
  HOME_IMPROVEMENT_FURNITURE: "HOME_IMPROVEMENT",
  HOME_IMPROVEMENT_HARDWARE: "HOME_IMPROVEMENT",
  HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE: "HOME_IMPROVEMENT",
  HOME_IMPROVEMENT_SECURITY: "HOME_IMPROVEMENT",
  HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT: "HOME_IMPROVEMENT",

  // Medical
  MEDICAL_DENTAL_CARE: "MEDICAL",
  MEDICAL_EYE_CARE: "MEDICAL",
  MEDICAL_NURSING_CARE: "MEDICAL",
  MEDICAL_PHARMACIES_AND_SUPPLEMENTS: "MEDICAL",
  MEDICAL_PRIMARY_CARE: "MEDICAL",
  MEDICAL_VETERINARY_SERVICES: "MEDICAL",
  MEDICAL_OTHER_MEDICAL: "MEDICAL",

  // Personal Care
  PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS: "PERSONAL_CARE",
  PERSONAL_CARE_HAIR_AND_BEAUTY: "PERSONAL_CARE",
  PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING: "PERSONAL_CARE",
  PERSONAL_CARE_OTHER_PERSONAL_CARE: "PERSONAL_CARE",

  // General Services
  GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING: "GENERAL_SERVICES",
  GENERAL_SERVICES_AUTOMOTIVE: "GENERAL_SERVICES",
  GENERAL_SERVICES_CHILDCARE: "GENERAL_SERVICES",
  GENERAL_SERVICES_CONSULTING_AND_LEGAL: "GENERAL_SERVICES",
  GENERAL_SERVICES_EDUCATION: "GENERAL_SERVICES",
  GENERAL_SERVICES_INSURANCE: "GENERAL_SERVICES",
  GENERAL_SERVICES_POSTAGE_AND_SHIPPING: "GENERAL_SERVICES",
  GENERAL_SERVICES_STORAGE: "GENERAL_SERVICES",
  GENERAL_SERVICES_OTHER_GENERAL_SERVICES: "GENERAL_SERVICES",

  // Government & Non-Profit
  GOVERNMENT_AND_NON_PROFIT_DONATIONS: "GOVERNMENT_AND_NON_PROFIT",
  GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES: "GOVERNMENT_AND_NON_PROFIT",
  GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT: "GOVERNMENT_AND_NON_PROFIT",
  GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT: "GOVERNMENT_AND_NON_PROFIT",

  // Transportation
  TRANSPORTATION_BIKES_AND_SCOOTERS: "TRANSPORTATION",
  TRANSPORTATION_GAS: "TRANSPORTATION",
  TRANSPORTATION_PARKING: "TRANSPORTATION",
  TRANSPORTATION_PUBLIC_TRANSIT: "TRANSPORTATION",
  TRANSPORTATION_TAXIS_AND_RIDE_SHARES: "TRANSPORTATION",
  TRANSPORTATION_TOLLS: "TRANSPORTATION",
  TRANSPORTATION_OTHER_TRANSPORTATION: "TRANSPORTATION",

  // Travel
  TRAVEL_FLIGHTS: "TRAVEL",
  TRAVEL_LODGING: "TRAVEL",
  TRAVEL_RENTAL_CARS: "TRAVEL",
  TRAVEL_OTHER_TRAVEL: "TRAVEL",

  // Rent & Utilities (Housing)
  RENT_AND_UTILITIES_GAS_AND_ELECTRICITY: "RENT_AND_UTILITIES",
  RENT_AND_UTILITIES_INTERNET_AND_CABLE: "RENT_AND_UTILITIES",
  RENT_AND_UTILITIES_RENT: "RENT_AND_UTILITIES",
  RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT: "RENT_AND_UTILITIES",
  RENT_AND_UTILITIES_TELEPHONE: "RENT_AND_UTILITIES",
  RENT_AND_UTILITIES_WATER: "RENT_AND_UTILITIES",
  RENT_AND_UTILITIES_OTHER_UTILITIES: "RENT_AND_UTILITIES",
};

// Group derivation. Income + transfers-in are "Income"; everything else is
// "Expenses". Transfers-out are noise but we keep them in Expenses for
// completeness; the user can simply leave them unbudgeted.
export function groupOf(primary: PfcPrimary): PfcGroup {
  if (primary === "INCOME" || primary === "TRANSFER_IN") return "INCOME";
  return "EXPENSES";
}

// Friendly display names for primary categories.
export const PRIMARY_NAME: Record<PfcPrimary, string> = {
  INCOME: "Income",
  TRANSFER_IN: "Transfers In",
  TRANSFER_OUT: "Transfers Out",
  LOAN_PAYMENTS: "Loans",
  BANK_FEES: "Bank Fees",
  ENTERTAINMENT: "Entertainment",
  FOOD_AND_DRINK: "Food & Dining",
  GENERAL_MERCHANDISE: "Shopping",
  HOME_IMPROVEMENT: "Home Improvement",
  MEDICAL: "Medical",
  PERSONAL_CARE: "Personal Care",
  GENERAL_SERVICES: "Services",
  GOVERNMENT_AND_NON_PROFIT: "Taxes & Giving",
  TRANSPORTATION: "Transportation",
  TRAVEL: "Travel",
  RENT_AND_UTILITIES: "Housing & Utilities",
};

// Convert a Plaid detailed code into a human label by stripping its primary
// prefix and Title-Casing the remainder. "FOOD_AND_DRINK_GROCERIES" → "Groceries".
// "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK" → "Other".
export function detailedName(detailed: string): string {
  const primary = PFC_DETAILED[detailed];
  if (!primary) return titleCaseFromSnake(detailed);
  let leaf = detailed.slice(primary.length + 1);
  // Collapse trailing "OTHER_<primary>" to just "Other".
  const otherSuffix = `OTHER_${primary}`;
  if (leaf === otherSuffix) leaf = "OTHER";
  return titleCaseFromSnake(leaf);
}

function titleCaseFromSnake(s: string): string {
  return s
    .toLowerCase()
    .split("_")
    .map((w) => (w === "and" ? "&" : w.charAt(0).toUpperCase() + w.slice(1)))
    .join(" ");
}

// All detailed codes that belong to a given primary, sorted alphabetically by
// friendly name for stable display order.
export function detailedFor(primary: PfcPrimary): string[] {
  return Object.entries(PFC_DETAILED)
    .filter(([, p]) => p === primary)
    .map(([d]) => d)
    .sort((a, b) => detailedName(a).localeCompare(detailedName(b)));
}

// All primary codes for a given group, in display order.
export function primariesFor(group: PfcGroup): PfcPrimary[] {
  return PLAID_PFC_PRIMARY.filter((p) => groupOf(p) === group);
}
